# 配置输出日志
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    io.seata: DEBUG
    org.springframework.cloud.alibaba.seata.web: DEBUG

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

custom:
  test-value: local

ribbon:
  filter:
    metadata:
      enabled: false

spring:
  jpa:
    show-sql: true
    format-sql: true
  datasource:
    url: jdbc:mysql://xxx/db_storage?characterEncoding=UTF-8&useSSL=false
    username: xxx
    password: xxx
